export const flats = [
    {
        id: 1,
        title: '01',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 2,
        title: '02',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 3,
        title: '03',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 4,
        title: '04',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 5,
        title: '05',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 6,
        title: '06',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 7,
        title: '08',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 9,
        title: '09',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 10,
        title: '10',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 11,
        title: '11',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 12,
        title: '12',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 13,
        title: '13',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 14,
        title: '14',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
    {
        id: 15,
        title: '15',
        sqft: parseFloat((Math.random() * (150 - 50) + 50).toFixed(2)),
        netArea: parseFloat((Math.random() * (150) + 50).toFixed(2)),
        type: '2+1',
        available: ['available', 'rent', 'sold'][Math.floor(Math.random() * 3)],
        floor: Math.floor(Math.random() * 9) + 1,
        balcony: Math.floor(Math.random() * 2),
    },
]